### ISSUE TITLE
PHP Version issue

### ISSUE THREAD

**Issue by 0x13ens** [ProbablyRational/wasabi-storage#7]
I'm using the Latest Laravel version and keep getting this error:

` [InvalidArgumentException]
  Could not find package probablyrational/wasabi-storage in any version matching your PHP version, PHP extensions and Composer version`

**Comment by harshnavadiya** [comment]
![Capture](https://user-images.githubusercontent.com/39731339/129198448-2f4f2a8f-8400-4fbf-9f0c-b96ecc97a160.PNG)

 [InvalidArgumentException]
  Package probablyrational/wasabi-storage has a PHP requirement incompatible with your PHP version, PHP extensions an
  d Composer version:
    - probablyrational/wasabi-storage requires php ^7.2 which does not match your installed version 8.0.9.
    - probablyrational/wasabi-storage requires illuminate/support ^6.0|^7.0|^8.0 but it is not present.
    - probablyrational/wasabi-storage requires illuminate/filesystem ^6.0|^7.0|^8.0 but it is not present.
    - probablyrational/wasabi-storage requires league/flysystem-aws-s3-v3 ^1.0 but it is not present.


I'm getting the same error 
--------------------------------------------------
       Composer version 2.1.3


        "php": "^7.3|^8.0",
        "laravel/framework": "^8.12",
