### ISSUE TITLE
version  Issue

### ISSUE THREAD

**Issue by harshnavadiya** [ProbablyRational/wasabi-storage#8]
--------------------------------------------------
       Composer version 2.1.3

        "php": "^7.3|^8.0",

        "laravel/framework": "^8.12",

![Capture](https://user-images.githubusercontent.com/39731339/129199516-254cd89a-e2fa-4572-b821-72e71166007a.PNG)

**Comment by hcaz** [comment]
Hi @harshnavadiya sorry for the delay. I have just pushed version 1.4.0.rc which has an updated PHP requirment. If you can test this and let me know if you have any issues. If not I will push that version to be public.
